name: in-context-learning
channels:
  - pytorch
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.10.13
  - pytorch=2.2.0
  - pip:
    - pyyaml==6.0.1
    - scikit-learn==1.0.2
    - tqdm==4.64.0
    - transformers==4.39.3
    - wandb==0.12.11
    - xgboost==1.6.1
    - protobuf==3.20.1
